sources:
  oracle:
    thick:
      # Oracle Instant Client 경로 (Thick mode)
      instant_client: "C:\\Users\\thrus\\Downloads\\WINDOWS.X64_213000_db_home1\\bin"

    # 기본 실행 대상 host (CLI --hosts로 override 가능)
    run:
      hosts:
        - local
        # - host2
    export:
      fetch_size: 20000
      timeout_seconds: 1800  # 30분 (기본값)

    # host별 Oracle 접속 정보
    hosts:
      local:
        dsn: 127.0.0.1:1521/ORCLPDB                # tnsnames.ora alias 또는 EZCONNECT # 그대로 사용하려면 hostname:port/servicename로 입력
        user: tester
        password: "aa12345"
        duckdb_schema: local                      # 생략할 경우 hosts[local] 과 동일

      operation:
        dsn: 10.150.4.110:1523/PIFSODBS
        user: U1116338
        password: "aa12345!"
        duckdb_schema: IFRSN     

  vertica:
    run:
      hosts:
        - pdwvdbs
    export:
      fetch_size: 50000

    hosts:
      pdwvdbs:
        host: 10.150.4.75
        port: 5433
        database: PDWVDBS
        user: U1116338
        password: "ehruddl89@"
        tlsmode: disable
        duckdb_schema: NGSUSR